on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Name of the repository to create"
        required: true
      description:
        description: "Description of the repository"
        required: false
        default: "Created via GitHub Actions"

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Repository
        run: |
          curl -X POST https://api.github.com/user/repos \
          -H "Authorization: token ${{ secrets.pat_token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{
            \"name\": \"${{ github.event.inputs.repo-name }}\",
            \"description\": \"${{ github.event.inputs.description }}\",
            \"private\": false
          }"